# Site settings
title: Stella Site Title
description: A brief description of your site
baseurl: "/blog" # the subpath of your site, e.g., /blog
url: "https://gionatamettifogo.github.io/blog/" # the base hostname & protocol for your site, e.g., http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from production build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
